### ISSUE TITLE
superposition of elements at http://zero.sjeng.org/opening

### ISSUE THREAD

**Issue by NodosDsnn** [leela-zero/leela-zero#2291]
the content is superimposed on the menu above the scroll.

![x](https://user-images.githubusercontent.com/8846745/54651504-ee493800-4a91-11e9-9b75-ea3e1fdba9b2.png)

it can be solved by adjusting the z-index of the css.

```css
/* in vuetify.min.css */
.application .theme--dark.toolbar, .theme--dark .toolbar {
    background-color: #212121;
    color: #fff;
    z-index: 1000; /* solution */
}
```
